---
metadata:
  name: 홍원의 블로그
  short_name: wehong
  description: wehong's blog
  language: en
  pathPrefix: "/"
  siteImage:
  favicon: "/assets/favicon.png"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "/assets/code.svg"
  logoLink: "/"
  helpUrl: ""
  links:
#    - text: Nota. Inc
#      link: https://nota.ai/
#      external: true
#    - text: DPlus
#      link: http://www.dplus.company/
#      external: true
#    - text: AC2
#      link: "http://www.ac2.kr/"
#      external: true
sidebar:
  enabled: true
  # forcedNavOrder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: "/1_retrospective"
      title: ":rocket: 회고 retrospective"
    - order: 2
      path: "/2_onepageml"
      title: ":robot_face: 한페이지 머신러닝"
    - order: 3
      path: "/3_onepagehl"
      title: ":writing_hand: 그림일기"
    - order: 4
      path: "/4_agilecoach"
      title: ":rocket: Agile Coach"
    - order: 5
      path: "/5_developing"
      title: ":computer: 개발"
    - order: 6
      path: "/writing"
      title: ":rocket: 글쓰기"
#    - order: 7
#      path: "/configuration"
#      title: ":wrench: Configuration"
#    - order: 8
#      path: "/editing"
#      title: ":writing_hand: Editing Content"
#    - order: 9
#      path: "/deployment"
#      title: ":rocket: Deployment"
#    - order: 10
#      path: "/developing"
#      title: ":computer: Developing"
  links:
    - text: Nota. Inc
      link: https://nota.ai/
      external: true
    - text: DPlus
      link: http://www.dplus.company/
      external: true
    - text: AC2
      link: "http://www.ac2.kr/"
      external: true
  ignoreIndex: false
#  poweredBy:
#    trademark: "/assets/gatsby.png"
#    name: GatsbyJS
#    link: https://www.gatsbyjs.org
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/favicon.png"

social:
  facebook: https://www.facebook.com/woneui.hong
  github: https://github.com/filipowm/boogi
  linkedin: https://www.linkedin.com/in/mateusz-filipowicz-437b4768/
  twitter: twitter url

features:
  darkMode:
    enabled: true
    default: true
  editOnRepo:
    location: https://github.com/laftworld/BooGi
    type: github
    editable: true
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: true
    title: BooGi Docs
    showIcon: false
    copyright: "2020, Mateusz Filipowicz"
    webMaster: "Mateusz Filipowicz"
    managingEditor: "Mateusz Filipowicz"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: true
    engine: 'algolia'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode:
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
